# Generated by Django 4.0.5 on 2022-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('F', 'Física '), ('J', 'Jurídica')], default='M', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nenhuma das opções')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
